import { StyleSheet, Platform, Dimensions } from 'react-native';
import { Radius, Spacing } from '@/constants/theme';

const { width } = Dimensions.get('window');

export const DetailStyles = StyleSheet.create({
  container: { flex: 1 },
  safeArea: { flex: 1 },
  scrollContent: { paddingBottom: 40 },
  floatingHeader: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 50 : 20,
    left: 20,
    right: 20,
    zIndex: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  roundButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 3,
  },
  heroImage: {
    width: width,
    height: width * 1.2,
    resizeMode: 'cover',
  },
  mainContent: {
    marginTop: -30,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    padding: Spacing.lg,
    minHeight: 500,
  },
  badgeRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
  },
  badge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
  },
  badgeText: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  title: {
    fontSize: 28,
    fontWeight: '800',
    lineHeight: 34,
    marginBottom: 6,
  },
  author: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 24,
  },
  infoGrid: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
  },
  infoCard: {
    flex: 1,
    padding: 16,
    borderRadius: Radius.lg,
    borderWidth: 1,
  },
  infoCardWide: {
    width: '100%',
    padding: 16,
    borderRadius: Radius.lg,
    borderWidth: 1,
    marginBottom: 32,
  },
  infoLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#94A3B8',
    marginBottom: 6,
    letterSpacing: 1,
  },
  infoValue: {
    fontSize: 15,
    fontWeight: '800',
  },
  tagContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
  },
  majorTag: {
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  majorTagText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#475569',
  },
  section: {
    marginBottom: 32,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 12,
  },
  description: {
    fontSize: 15,
    lineHeight: 24,
    fontWeight: '500',
  },
  donorCard: {
    padding: 20,
    borderRadius: Radius.lg,
    marginBottom: 32,
  },
  donorSection: {
    padding: 20,
    borderRadius: Radius.lg,
    marginBottom: 32,
  },
  donorLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: '#94A3B8',
    letterSpacing: 1,
    marginBottom: 16,
  },
  smallLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: '#94A3B8',
    letterSpacing: 1,
    marginBottom: 16,
  },
  donorHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 20,
  },
  donorAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#E2E8F0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarImg: {
    width: 50,
    height: 50,
    borderRadius: 25,
  },
  donorInfo: {
    flex: 1,
    justifyContent: 'center',
  },
  donorName: {
    fontSize: 17,
    fontWeight: '800',
  },
  donorSubtitle: {
    fontSize: 13,
    color: '#64748B',
    fontWeight: '600',
  },
  donorSubtext: {
    fontSize: 13,
    color: '#64748B',
    fontWeight: '500',
    marginTop: 2,
  },
  donorMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
  },
  donorMetaText: {
    fontSize: 14,
    color: '#475569',
    fontWeight: '500',
  },
  viewProfileBtn: {
    marginTop: 16,
    height: 48,
    borderRadius: Radius.md,
    backgroundColor: '#E2E8F0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  viewProfileText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#475569',
  },
  exploreLink: {
    fontSize: 14,
    fontWeight: '700',
  },
  horizontalScroll: {
    marginLeft: -Spacing.lg,
    paddingLeft: Spacing.lg,
  },
  otherBookCard: {
    width: 140,
    marginRight: 16,
  },
  otherBookImage: {
    width: 140,
    height: 180,
    borderRadius: Radius.md,
    marginBottom: 8,
  },
  otherBookTitle: {
    fontSize: 14,
    fontWeight: '800',
    marginBottom: 2,
  },
  otherBookAuthor: {
    fontSize: 12,
    color: '#64748B',
    fontWeight: '600',
  },
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingTop: 12,
    paddingBottom: Platform.OS === 'ios' ? 34 : 20,
    paddingHorizontal: 20,
    borderTopWidth: 1,
  },
  bottomBarInner: {
    flexDirection: 'row',
    gap: 12,
  },
  requestBtn: {
    flex: 1,
    height: 56,
    borderRadius: Radius.pill,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  requestBtnText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '800',
  },
  messageBtn: {
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backBtn: {
    marginTop: 20,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: Radius.pill,
    backgroundColor: '#F1F5F9',
  },
  backBtnText: {
    fontWeight: '700',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    width: '100%',
    borderRadius: 24,
    padding: 24,
    alignItems: 'center',
  },
  modalHeader: {
    alignItems: 'center',
    marginBottom: 24,
  },
  iconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: '800',
    marginBottom: 12,
  },
  modalSubtitle: {
    fontSize: 15,
    color: '#64748B',
    textAlign: 'center',
    lineHeight: 22,
    fontWeight: '500',
  },
  modalDivider: {
    width: '100%',
    height: 1,
    backgroundColor: '#F1F5F9',
    marginBottom: 24,
  },
  modalFooter: {
    flexDirection: 'row',
    gap: 12,
    width: '100%',
  },
  cancelBtn: {
    flex: 1,
    height: 52,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: Radius.md,
    backgroundColor: '#F1F5F9',
  },
  cancelBtnText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#64748B',
  },
  confirmBtn: {
    flex: 2,
    height: 52,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: Radius.md,
  },
  confirmBtnText: {
    fontSize: 15,
    fontWeight: '800',
    color: '#FFF',
  },
});
