import { BookDetail } from '@/src/features/book_details/types';

export const MOCK_SOURCES: BookDetail[] = [
  {
    id: 'mock-1',
    title: 'Calculus: Early Transcendentals',
    titleAr: 'حساب التفاضل والتكامل: البدايات المتسامية',
    courseName: 'MATH101',
    facultyId: 'sci',
    facultyIds: ['sci', 'eng'],
    major: 'Mathematics / Engineering',
    conditionId: 'like_new',
    description: 'A comprehensive guide to calculus. Practically brand new, only used for one semester. No highlights or markings inside.',
    descriptionAr: 'دليل شامل لحساب التفاضل والتكامل. جديد تقريباً، استُخدم لفصل دراسي واحد فقط. لا يوجد أي تحديد أو علامات بالداخل.',
    imageUrl: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?q=80&w=1000&auto=format&fit=crop',
    donorName: 'Ahmed Fathi',
    donorUid: 'user-1',
    author: 'James Stewart',
    edition: '8th Edition',
    categoryId: 'books',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'mock-2',
    title: 'Data Structures & Algorithms Notes',
    titleAr: 'تلخيص تراكيب البيانات والخوارزميات',
    courseName: 'CS210',
    facultyId: 'it',
    facultyIds: ['it'],
    major: 'Computer Science',
    conditionId: 'good',
    description: 'Detailed handwritten notes covering Linked Lists, Trees, Graphs, and Sorting algorithms. Very helpful for final exams.',
    descriptionAr: 'ملاحظات مكتوبة بخط اليد بالتفصيل تغطي القوائم المترابطة، الأشجار، الرسوم البيانية، وخوارزميات الترتيب. مفيدة جداً للامتحانات النهائية.',
    imageUrl: 'https://images.unsplash.com/photo-1517842645767-c639042777db?q=80&w=1000&auto=format&fit=crop',
    donorName: 'Sara Ali',
    donorUid: 'user-2',
    categoryId: 'notes',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'mock-3',
    title: 'Arduino Uno Ultimate Starter Kit',
    titleAr: 'حقيبة أردوينو أونو التعليمية',
    courseName: 'EE200',
    facultyId: 'eng',
    facultyIds: ['eng', 'it'],
    major: 'Electrical Engineering',
    conditionId: 'new',
    description: 'Complete kit including Arduino Uno R3, breadboard, sensors, LEDs, and jumper wires. Everything you need for the Intro to Embedded Systems course.',
    descriptionAr: 'حقيبة كاملة تشمل أردوينو أونو R3، لوحة تجارب، مستشعرات، ومؤشرات ضوئية وأسلاك توصيل. كل ما تحتاجه لمساق مقدمة في الأنظمة المدمجة.',
    imageUrl: 'https://images.unsplash.com/photo-1553406830-ef2513450d76?q=80&w=1000&auto=format&fit=crop',
    donorName: 'Omar Hassan',
    donorUid: 'user-3',
    categoryId: 'hardware',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'mock-4',
    title: 'Casio FX-991EX ClassWiz',
    titleAr: 'آلة حاسبة كاسيو FX-991EX',
    courseName: 'ALL',
    facultyId: 'all',
    facultyIds: ['all'],
    major: 'General',
    conditionId: 'good',
    description: 'Advanced scientific calculator. Perfect for engineering and science students. Battery is still strong.',
    descriptionAr: 'آلة حاسبة علمية متطورة. مثالية لطلاب الهندسة والعلوم. البطارية لا تزال قوية.',
    imageUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=1000&auto=format&fit=crop',
    donorName: 'Layla Mahmoud',
    donorUid: 'user-4',
    categoryId: 'others',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'mock-6',
    title: 'Marketing Management Summary',
    titleAr: 'ملخص إدارة التسويق',
    courseName: 'BUS302',
    facultyId: 'bus',
    facultyIds: ['bus'],
    major: 'Business Administration',
    conditionId: 'new',
    description: 'Short and precise summary for the midterm and final exams. Covers all 12 chapters.',
    descriptionAr: 'ملخص قصير ودقيق للامتحانات النصفية والنهائية. يغطي جميع الفصول الـ 12.',
    imageUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?q=80&w=1000&auto=format&fit=crop',
    donorName: 'Mona Khaled',
    donorUid: 'user-6',
    categoryId: 'notes',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'mock-8',
    title: 'Criminal Law Lecture Notes',
    titleAr: 'ملخص محاضرات القانون الجنائي',
    courseName: 'LAW205',
    facultyId: 'law',
    facultyIds: ['law'],
    major: 'Law',
    conditionId: 'good',
    description: 'Comprehensive notes from Dr. Ahmed lectures. Includes previous exam questions and cases.',
    descriptionAr: 'ملاحظات شاملة من محاضرات الدكتور أحمد. تتضمن أسئلة امتحانات سابقة وقضايا قانونية.',
    imageUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?q=80&w=1000&auto=format&fit=crop',
    donorName: 'Noor Jaber',
    donorUid: 'user-8',
    categoryId: 'notes',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'mock-9',
    title: 'Python for Data Science Guide',
    titleAr: 'دليل لغة بايثون لعلوم البيانات',
    courseName: 'CS315',
    facultyId: 'it',
    facultyIds: ['it', 'sci'],
    major: 'Computer Science / AI',
    conditionId: 'new',
    description: 'A great book for beginners. Covers Pandas, Numpy, and Matplotlib with practical examples.',
    descriptionAr: 'كتاب رائع للمبتدئين. يغطي مكتبات Pandas و Numpy و Matplotlib مع أمثلة عملية.',
    imageUrl: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?q=80&w=1000&auto=format&fit=crop',
    donorName: 'Hasan Ali',
    donorUid: 'user-9',
    author: 'Jake VanderPlas',
    edition: '2023 Edition',
    categoryId: 'books',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'mock-10',
    title: 'Lab Coat & Safety Goggles',
    titleAr: 'لاب كوت ونظارات حماية',
    courseName: 'LAB101',
    facultyId: 'sci',
    facultyIds: ['sci', 'med', 'pha', 'den'],
    major: 'Science / Health',
    conditionId: 'good',
    description: 'Size Medium. Used for one semester in the Bio lab. Clean and ready for use.',
    descriptionAr: 'مقاس وسط (M). استخدم لفصل واحد في مختبر الأحياء. نظيف وجاهز للاستخدام.',
    imageUrl: 'https://images.unsplash.com/photo-1581093588401-fbb62a02f120?q=80&w=1000&auto=format&fit=crop',
    donorName: 'Lina Murad',
    donorUid: 'user-10',
    categoryId: 'hardware',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'mock-12',
    title: 'Digital Multimeter',
    titleAr: 'ملتيميتر رقمي (جهاز فحص)',
    courseName: 'EE210',
    facultyId: 'eng',
    facultyIds: ['eng', 'it'],
    major: 'Electrical / Electronics',
    conditionId: 'good',
    description: 'Handy tool for electronics lab. Measures Voltage, Current, and Resistance. Includes probes.',
    descriptionAr: 'أداة مفيدة لمختبر الإلكترونيات. يقيس الجهد والتيار والمقاومة. يشمل أسلاك الفحص.',
    imageUrl: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?q=80&w=1000&auto=format&fit=crop',
    donorName: 'Kareem Issa',
    donorUid: 'user-12',
    categoryId: 'hardware',
    createdAt: new Date().toISOString(),
  }
];
