import { Store, Offer } from './types';

export const MOCK_STORES: Store[] = [
  {
    id: 'store_001',
    name: 'Al-Najah Bookstore',
    logoUrl: 'https://ui-avatars.com/api/?name=NB&background=001B39&color=fff&size=128&bold=true',
    location: { address: 'Main Gate – An-Najah University, Nablus' },
    phone: '0595-000-111',
    isApproved: true,
    rating: 4.8,
    totalOffers: 12,
    createdAt: '2026-01-10',
    description: 'Official academic bookstore serving An-Najah students since 1980.',
  },
  {
    id: 'store_002',
    name: 'Qirtas Stationery',
    logoUrl: 'https://ui-avatars.com/api/?name=QS&background=0EA5E9&color=fff&size=128&bold=true',
    location: { address: 'West Campus – Near Engineering Faculty' },
    phone: '0596-222-333',
    isApproved: true,
    rating: 4.5,
    totalOffers: 8,
    createdAt: '2026-02-05',
    description: 'Your one-stop shop for pens, notebooks, and study supplies.',
  },
  {
    id: 'store_003',
    name: 'TechDesk Electronics',
    logoUrl: 'https://ui-avatars.com/api/?name=TD&background=10B981&color=fff&size=128&bold=true',
    location: { address: 'IT Building – Ground Floor' },
    phone: '0597-444-555',
    isApproved: true,
    rating: 4.6,
    totalOffers: 5,
    createdAt: '2026-03-15',
    description: 'Cables, adapters, and accessories for IT & Engineering students.',
  },
];

export const MOCK_OFFERS: Offer[] = [
  {
    id: 'offer_001',
    storeId: 'store_001',
    storeName: 'Al-Najah Bookstore',
    storeLogoUrl: MOCK_STORES[0].logoUrl,
    title: 'Data Structures & Algorithms',
    description: 'The definitive academic textbook for CS students. Covers arrays, trees, graphs and sorting algorithms.',
    category: 'books',
    imageUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=300&fit=crop',
    originalPrice: 70,
    discountedPrice: 60,
    commissionValue: 5,
    commissionType: 'fixed',
    isActive: true,
    stock: 15,
    validUntil: '2026-08-01',
    createdAt: '2026-06-01',
    isFeatured: true,
  },
  {
    id: 'offer_002',
    storeId: 'store_001',
    storeName: 'Al-Najah Bookstore',
    storeLogoUrl: MOCK_STORES[0].logoUrl,
    title: 'Calculus – Early Transcendentals',
    description: 'Stewart Calculus 8th Edition. Required for Engineering and Math students.',
    category: 'books',
    imageUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400&h=300&fit=crop',
    originalPrice: 85,
    discountedPrice: 72,
    commissionValue: 7,
    commissionType: 'fixed',
    isActive: true,
    stock: 8,
    validUntil: '2026-07-15',
    createdAt: '2026-06-03',
    isFeatured: true,
  },
  {
    id: 'offer_003',
    storeId: 'store_002',
    storeName: 'Qirtas Stationery',
    storeLogoUrl: MOCK_STORES[1].logoUrl,
    title: 'Premium Study Bundle',
    description: '5 notebooks, highlighters set, 2 pens, sticky notes — everything you need for a semester.',
    category: 'bundles',
    imageUrl: 'https://images.unsplash.com/photo-1585776245991-cf89dd7fc73a?w=400&h=300&fit=crop',
    originalPrice: 45,
    discountedPrice: 35,
    commissionValue: 4,
    commissionType: 'fixed',
    isActive: true,
    stock: 30,
    validUntil: '2026-09-01',
    createdAt: '2026-06-05',
    isFeatured: true,
  },
  {
    id: 'offer_004',
    storeId: 'store_002',
    storeName: 'Qirtas Stationery',
    storeLogoUrl: MOCK_STORES[1].logoUrl,
    title: 'A4 Copy Paper (500 sheets)',
    description: '80gsm white printing paper, perfect for assignment and lab reports.',
    category: 'stationery',
    imageUrl: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=300&fit=crop',
    originalPrice: 18,
    discountedPrice: 14,
    commissionValue: 2,
    commissionType: 'fixed',
    isActive: true,
    stock: 100,
    validUntil: '2026-12-31',
    createdAt: '2026-06-08',
    isFeatured: false,
  },
  {
    id: 'offer_005',
    storeId: 'store_003',
    storeName: 'TechDesk Electronics',
    storeLogoUrl: MOCK_STORES[2].logoUrl,
    title: 'USB-C Hub (7-in-1)',
    description: 'Compatible with laptops and tablets. Includes HDMI, USB 3.0, SD card reader.',
    category: 'electronics',
    imageUrl: 'https://images.unsplash.com/photo-1625891825975-d7ca1c5a1c63?w=400&h=300&fit=crop',
    originalPrice: 120,
    discountedPrice: 99,
    commissionValue: 10,
    commissionType: 'fixed',
    isActive: true,
    stock: 10,
    validUntil: '2026-07-31',
    createdAt: '2026-06-10',
    isFeatured: true,
  },
  {
    id: 'offer_006',
    storeId: 'store_001',
    storeName: 'Al-Najah Bookstore',
    storeLogoUrl: MOCK_STORES[0].logoUrl,
    title: 'Engineering Drawing Set',
    description: 'Full set: compass, protractor, ruler, set squares and pencils.',
    category: 'tools',
    imageUrl: 'https://images.unsplash.com/photo-1503551723145-6c040742065b?w=400&h=300&fit=crop',
    originalPrice: 55,
    discountedPrice: 44,
    commissionValue: 5,
    commissionType: 'fixed',
    isActive: true,
    stock: 20,
    validUntil: '2026-08-15',
    createdAt: '2026-06-12',
    isFeatured: false,
  },
];
