import { Store, Offer } from './types';

// ─────────────────────────────────────────────
// AN-NAJAH (live pilot data)
// ─────────────────────────────────────────────

export const MOCK_STORES_NAJAH: Store[] = [
  {
    id: 'store_001',
    name: 'Al-Najah Bookstore',
    logoUrl: 'https://ui-avatars.com/api/?name=NB&background=001B39&color=fff&size=128&bold=true',
    location: { address: 'Main Gate – An-Najah University, Nablus' },
    phone: '0595-000-111',
    isApproved: true,
    rating: 4.8,
    totalOffers: 4,
    createdAt: '2026-01-10',
    description: 'Official academic bookstore serving An-Najah students since 1980.',
    universityId: 'najah',
  },
  {
    id: 'store_002',
    name: 'Qirtas Stationery',
    logoUrl: 'https://ui-avatars.com/api/?name=QS&background=0EA5E9&color=fff&size=128&bold=true',
    location: { address: 'West Campus – Near Engineering Faculty' },
    phone: '0596-222-333',
    isApproved: true,
    rating: 4.5,
    totalOffers: 2,
    createdAt: '2026-02-05',
    description: 'Your one-stop shop for pens, notebooks, and study supplies.',
    universityId: 'najah',
  },
  {
    id: 'store_003',
    name: 'TechDesk Electronics',
    logoUrl: 'https://ui-avatars.com/api/?name=TD&background=10B981&color=fff&size=128&bold=true',
    location: { address: 'IT Building – Ground Floor' },
    phone: '0597-444-555',
    isApproved: true,
    rating: 4.6,
    totalOffers: 2,
    createdAt: '2026-03-15',
    description: 'Cables, adapters, and accessories for IT & Engineering students.',
    universityId: 'najah',
  },
];

export const MOCK_OFFERS_NAJAH: Offer[] = [
  {
    id: 'offer_001',
    storeId: 'store_001',
    storeName: 'Al-Najah Bookstore',
    storeLogoUrl: MOCK_STORES_NAJAH[0].logoUrl,
    title: 'Data Structures & Algorithms',
    description: 'The definitive academic textbook for CS students. Covers arrays, trees, graphs and sorting algorithms.',
    category: 'books',
    imageUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=300&fit=crop',
    originalPrice: 70,
    discountedPrice: 60,
    commissionValue: 5,
    commissionType: 'fixed',
    isActive: true,
    stock: 15,
    validUntil: '2026-08-01',
    createdAt: '2026-06-01',
    isFeatured: true,
    universityId: 'najah',
  },
  {
    id: 'offer_002',
    storeId: 'store_001',
    storeName: 'Al-Najah Bookstore',
    storeLogoUrl: MOCK_STORES_NAJAH[0].logoUrl,
    title: 'Calculus – Early Transcendentals',
    description: 'Stewart Calculus 8th Edition. Required for Engineering and Math students.',
    category: 'books',
    imageUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400&h=300&fit=crop',
    originalPrice: 85,
    discountedPrice: 72,
    commissionValue: 7,
    commissionType: 'fixed',
    isActive: true,
    stock: 8,
    validUntil: '2026-07-15',
    createdAt: '2026-06-03',
    isFeatured: true,
    universityId: 'najah',
  },
  {
    id: 'offer_003',
    storeId: 'store_002',
    storeName: 'Qirtas Stationery',
    storeLogoUrl: MOCK_STORES_NAJAH[1].logoUrl,
    title: 'Premium Study Bundle',
    description: '5 notebooks, highlighters set, 2 pens, sticky notes — everything you need for a semester.',
    category: 'bundles',
    imageUrl: 'https://images.unsplash.com/photo-1585776245991-cf89dd7fc73a?w=400&h=300&fit=crop',
    originalPrice: 45,
    discountedPrice: 35,
    commissionValue: 4,
    commissionType: 'fixed',
    isActive: true,
    stock: 30,
    validUntil: '2026-09-01',
    createdAt: '2026-06-05',
    isFeatured: true,
    universityId: 'najah',
  },
  {
    id: 'offer_004',
    storeId: 'store_002',
    storeName: 'Qirtas Stationery',
    storeLogoUrl: MOCK_STORES_NAJAH[1].logoUrl,
    title: 'A4 Copy Paper (500 sheets)',
    description: '80gsm white printing paper, perfect for assignment and lab reports.',
    category: 'stationery',
    imageUrl: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=300&fit=crop',
    originalPrice: 18,
    discountedPrice: 14,
    commissionValue: 2,
    commissionType: 'fixed',
    isActive: true,
    stock: 100,
    validUntil: '2026-12-31',
    createdAt: '2026-06-08',
    isFeatured: false,
    universityId: 'najah',
  },
  {
    id: 'offer_005',
    storeId: 'store_003',
    storeName: 'TechDesk Electronics',
    storeLogoUrl: MOCK_STORES_NAJAH[2].logoUrl,
    title: 'USB-C Hub (7-in-1)',
    description: 'Compatible with laptops and tablets. Includes HDMI, USB 3.0, SD card reader.',
    category: 'electronics',
    imageUrl: 'https://images.unsplash.com/photo-1625895197185-efcec01cffe0?w=400&h=300&fit=crop',
    originalPrice: 120,
    discountedPrice: 99,
    commissionValue: 10,
    commissionType: 'fixed',
    isActive: true,
    stock: 10,
    validUntil: '2026-07-31',
    createdAt: '2026-06-10',
    isFeatured: true,
    universityId: 'najah',
  },
  {
    id: 'offer_006',
    storeId: 'store_001',
    storeName: 'Al-Najah Bookstore',
    storeLogoUrl: MOCK_STORES_NAJAH[0].logoUrl,
    title: 'Engineering Drawing Set',
    description: 'Full set: compass, protractor, ruler, set squares and pencils.',
    category: 'tools',
    imageUrl: 'https://images.unsplash.com/photo-1503551723145-6c040742065b?w=400&h=300&fit=crop',
    originalPrice: 55,
    discountedPrice: 44,
    commissionValue: 5,
    commissionType: 'fixed',
    isActive: true,
    stock: 20,
    validUntil: '2026-08-15',
    createdAt: '2026-06-12',
    isFeatured: false,
    universityId: 'najah',
  },
  {
    id: 'offer_007',
    storeId: 'store_003',
    storeName: 'TechDesk Electronics',
    storeLogoUrl: MOCK_STORES_NAJAH[2].logoUrl,
    title: 'Wireless Bluetooth Headphones',
    description: 'Noise-cancelling, 30hr battery life. Great for study sessions.',
    category: 'electronics',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=300&fit=crop',
    originalPrice: 200,
    discountedPrice: 160,
    commissionValue: 15,
    commissionType: 'fixed',
    isActive: true,
    stock: 5,
    validUntil: '2026-09-30',
    createdAt: '2026-06-14',
    isFeatured: true,
    universityId: 'najah',
  },
];

// ─────────────────────────────────────────────
// ITALY PARTNER (preview environment)
// ─────────────────────────────────────────────

export const MOCK_STORES_ITALY: Store[] = [
  {
    id: 'it_store_001',
    name: 'Libreria Universitaria Roma',
    logoUrl: 'https://ui-avatars.com/api/?name=LR&background=009246&color=fff&size=128&bold=true',
    location: { address: 'Via della Sapienza 12, Rome, Italy' },
    phone: '+39-06-1234-5678',
    isApproved: true,
    rating: 4.7,
    totalOffers: 3,
    createdAt: '2026-03-01',
    description: 'Academic bookstore and stationery supplier for partner university students.',
    universityId: 'italy_partner',
  },
  {
    id: 'it_store_002',
    name: 'TechCampus Italia',
    logoUrl: 'https://ui-avatars.com/api/?name=TC&background=CE2B37&color=fff&size=128&bold=true',
    location: { address: 'Piazza della Tecnica 5, Milan, Italy' },
    phone: '+39-02-9876-5432',
    isApproved: true,
    rating: 4.4,
    totalOffers: 2,
    createdAt: '2026-04-10',
    description: 'Electronics, gadgets, and study accessories for tech students.',
    universityId: 'italy_partner',
  },
];

export const MOCK_OFFERS_ITALY: Offer[] = [
  {
    id: 'it_offer_001',
    storeId: 'it_store_001',
    storeName: 'Libreria Universitaria Roma',
    storeLogoUrl: MOCK_STORES_ITALY[0].logoUrl,
    title: 'Analisi Matematica I (Analysis I)',
    description: 'Standard Italian university calculus textbook used across engineering faculties.',
    category: 'books',
    imageUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=400&h=300&fit=crop',
    originalPrice: 65,
    discountedPrice: 50,
    commissionValue: 6,
    commissionType: 'fixed',
    isActive: true,
    stock: 12,
    validUntil: '2026-09-01',
    createdAt: '2026-06-01',
    isFeatured: true,
    universityId: 'italy_partner',
  },
  {
    id: 'it_offer_002',
    storeId: 'it_store_001',
    storeName: 'Libreria Universitaria Roma',
    storeLogoUrl: MOCK_STORES_ITALY[0].logoUrl,
    title: 'Premium Stationery Kit – EU',
    description: 'Complete academic kit: 4 notebooks, pens, highlighters, and a binder.',
    category: 'bundles',
    imageUrl: 'https://images.unsplash.com/photo-1456735190827-d1262f71b8a3?w=400&h=300&fit=crop',
    originalPrice: 42,
    discountedPrice: 32,
    commissionValue: 4,
    commissionType: 'fixed',
    isActive: true,
    stock: 25,
    validUntil: '2026-10-01',
    createdAt: '2026-06-05',
    isFeatured: true,
    universityId: 'italy_partner',
  },
  {
    id: 'it_offer_003',
    storeId: 'it_store_001',
    storeName: 'Libreria Universitaria Roma',
    storeLogoUrl: MOCK_STORES_ITALY[0].logoUrl,
    title: 'Fisica Generale (General Physics)',
    description: 'Halliday & Resnick Italian edition. Required for all science and engineering courses.',
    category: 'books',
    imageUrl: 'https://images.unsplash.com/photo-1532094349884-543559563b19?w=400&h=300&fit=crop',
    originalPrice: 72,
    discountedPrice: 58,
    commissionValue: 7,
    commissionType: 'fixed',
    isActive: true,
    stock: 9,
    validUntil: '2026-08-15',
    createdAt: '2026-06-08',
    isFeatured: false,
    universityId: 'italy_partner',
  },
  {
    id: 'it_offer_004',
    storeId: 'it_store_002',
    storeName: 'TechCampus Italia',
    storeLogoUrl: MOCK_STORES_ITALY[1].logoUrl,
    title: 'USB-C Multiport Adapter (8-in-1)',
    description: 'HDMI 4K, 3× USB-A, SD card, 100W PD charging. Compatible with all laptops.',
    category: 'electronics',
    imageUrl: 'https://images.unsplash.com/photo-1625895197185-efcec01cffe0?w=400&h=300&fit=crop',
    originalPrice: 89,
    discountedPrice: 72,
    commissionValue: 8,
    commissionType: 'fixed',
    isActive: true,
    stock: 15,
    validUntil: '2026-08-30',
    createdAt: '2026-06-10',
    isFeatured: true,
    universityId: 'italy_partner',
  },
  {
    id: 'it_offer_005',
    storeId: 'it_store_002',
    storeName: 'TechCampus Italia',
    storeLogoUrl: MOCK_STORES_ITALY[1].logoUrl,
    title: 'Laser Printer Paper A4 (500 sheets)',
    description: '90gsm bright white paper. Ideal for thesis printing and project submissions.',
    category: 'stationery',
    imageUrl: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&h=300&fit=crop',
    originalPrice: 16,
    discountedPrice: 12,
    commissionValue: 2,
    commissionType: 'fixed',
    isActive: true,
    stock: 80,
    validUntil: '2026-12-31',
    createdAt: '2026-06-12',
    isFeatured: false,
    universityId: 'italy_partner',
  },
];

// ─────────────────────────────────────────────
// FRANCE PARTNER (preview environment)
// ─────────────────────────────────────────────

export const MOCK_STORES_FRANCE: Store[] = [
  {
    id: 'fr_store_001',
    name: 'Librairie Campus Paris',
    logoUrl: 'https://ui-avatars.com/api/?name=LC&background=002395&color=fff&size=128&bold=true',
    location: { address: '15 Rue des Écoles, Paris, France' },
    phone: '+33-1-5555-6666',
    isApproved: true,
    rating: 4.6,
    totalOffers: 3,
    createdAt: '2026-03-20',
    description: 'Serving French partner university students with academic books and supplies.',
    universityId: 'france_partner',
  },
];

export const MOCK_OFFERS_FRANCE: Offer[] = [
  {
    id: 'fr_offer_001',
    storeId: 'fr_store_001',
    storeName: 'Librairie Campus Paris',
    storeLogoUrl: MOCK_STORES_FRANCE[0].logoUrl,
    title: 'Mathématiques Appliquées (Applied Math)',
    description: 'French edition – essential for sciences and engineering undergraduate programs.',
    category: 'books',
    imageUrl: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=400&h=300&fit=crop',
    originalPrice: 58,
    discountedPrice: 46,
    commissionValue: 5,
    commissionType: 'fixed',
    isActive: true,
    stock: 18,
    validUntil: '2026-09-15',
    createdAt: '2026-06-01',
    isFeatured: true,
    universityId: 'france_partner',
  },
  {
    id: 'fr_offer_002',
    storeId: 'fr_store_001',
    storeName: 'Librairie Campus Paris',
    storeLogoUrl: MOCK_STORES_FRANCE[0].logoUrl,
    title: 'Pack Rentrée Étudiant (Student Starter Pack)',
    description: 'Notebooks, pens, folders, and a planner. Everything for the new academic year.',
    category: 'bundles',
    imageUrl: 'https://images.unsplash.com/photo-1456735190827-d1262f71b8a3?w=400&h=300&fit=crop',
    originalPrice: 38,
    discountedPrice: 28,
    commissionValue: 4,
    commissionType: 'fixed',
    isActive: true,
    stock: 40,
    validUntil: '2026-10-01',
    createdAt: '2026-06-06',
    isFeatured: true,
    universityId: 'france_partner',
  },
  {
    id: 'fr_offer_003',
    storeId: 'fr_store_001',
    storeName: 'Librairie Campus Paris',
    storeLogoUrl: MOCK_STORES_FRANCE[0].logoUrl,
    title: 'Chimie Organique (Organic Chemistry)',
    description: 'Paula Bruice – French translated edition. Core textbook for all chemistry programs.',
    category: 'books',
    imageUrl: 'https://images.unsplash.com/photo-1532094349884-543559563b19?w=400&h=300&fit=crop',
    originalPrice: 80,
    discountedPrice: 64,
    commissionValue: 8,
    commissionType: 'fixed',
    isActive: true,
    stock: 7,
    validUntil: '2026-08-01',
    createdAt: '2026-06-10',
    isFeatured: false,
    universityId: 'france_partner',
  },
];

// ─────────────────────────────────────────────
// Combined exports (used by useMarketplace)
// ─────────────────────────────────────────────

export const MOCK_STORES: Store[] = [
  ...MOCK_STORES_NAJAH,
  ...MOCK_STORES_ITALY,
  ...MOCK_STORES_FRANCE,
];

export const MOCK_OFFERS: Offer[] = [
  ...MOCK_OFFERS_NAJAH,
  ...MOCK_OFFERS_ITALY,
  ...MOCK_OFFERS_FRANCE,
];
